experiment:
  num_runs: 1
  device: cuda
  seed: 42

wandb:
  enabled: true 
  project: length-generalization
  entity: null
  offline: false
  log_during_training: true
  log_final_only: false

dataset:
  # Training data - shorter sequences (1-10)
  train_min_range: 1
  train_max_range: 8 
  
  # Test/validation data - longer sequences (11-15)
  test_min_range: 9 
  test_max_range: 16
  
  # Dataset sizes
  train_samples: 500 
  val_samples: 200
  test_samples: 200
  
  # Vocabulary parameters
  vocab_size: 32 
  sep_token: 30 
  pad_token: 31 
  max_length: 32

model:
  d_model: 32
  n_layers: 2
  n_heads: 4
  d_ff: 64  # Smaller for pattern search as in original config
  max_len: 64
  dropout: 0.1  # No dropout for pattern search
  model_count: 16  # Smaller model count for faster experimentation
  init: regular

optimizer:
  name: PatternSearchFast
  # Training parameters
  epochs: 30000  # Reduced from 10000 for faster experiments
  es_acc: 0.99
  
  # Evaluation parameters
  eval_frequency: 100
