experiment:
  num_runs: 1
  device: cuda
  seed: 42

wandb:
  enabled: true 
  project: length-generalization
  entity: null
  offline: false
  log_during_training: true
  log_final_only: false

dataset:
  # Dataset type
  name: SortingDataset
  
  # Training data - shorter sequences (1-8)
  train_min_range: 1
  train_max_range: 8 
  
  # Test/validation data - longer sequences (9-16) 
  test_min_range: 9 
  test_max_range: 16
  
  # Dataset sizes
  train_samples: 500
  val_samples: 200
  test_samples: 200
  
  # Vocabulary parameters
  vocab_size: 32 
  sep_token: 30 
  pad_token: 31 
  max_length: 32

model:
  d_model: 32
  n_layers: 2
  n_heads: 4
  d_ff: 64 
  max_len: 64
  dropout: 0.1
  model_count: 1
  init: regular

optimizer:
  name: SGD
  
  # SGD parameters
  lr: 0.001
  momentum: 0.9
  batch_size: 128
  
  # Training parameters
  epochs: 400
  es_acc: 0.99
  
  # Evaluation parameters
  eval_frequency: 10