experiment:
  num_runs: 1
  device: cuda
  seed: 42

wandb:
  enabled: false 
  project: length-generalization
  entity: null
  offline: false
  log_during_training: true
  log_final: false

dataset:
  # Dataset type
  name: CopyDataset
  
  # Training data - shorter sequences (1-8)
  train_min_range: 1
  train_max_range: 4 
  
  # Test/validation data - longer sequences (9-16) 
  test_min_range: 5
  test_max_range: 8
  
  # Dataset sizes
  train_samples: 500
  val_samples: 200
  test_samples: 200
  
  # Vocabulary parameters
  vocab_size: 32 
  sep_token: 30 
  pad_token: 31 
  max_length: 32

model:
  d_model: 128
  n_layers: 2
  n_heads: 4
  d_ff: 256
  max_len: 32 
  dropout: 0.1
  model_count: 1
  init: regular
  position_encoding_type: absolute 
  rope_base: 10000

optimizer:
  name: SGD
  
  # SGD parameters
  lr: 0.001
  momentum: 0.9
  batch_size: 256 
  
  # Training parameters
  epochs: 800
  es_acc: 0.99
  
  # Evaluation parameters
  eval_frequency: 10