experiment:
  num_runs: 1
  device: cuda
  seed: 43

wandb:
  enabled: true 
  project: length-generalization
  entity: null
  offline: false
  log_during_training: true
  log_final_only: false

dataset:
  # Training data - shorter sequences (1-10)
  train_min_range: 1
  train_max_range: 5 
  
  # Test/validation data - longer sequences (11-15)
  test_min_range: 6 
  test_max_range: 10
  
  # Dataset sizes
  train_samples: 500 
  val_samples: 200
  test_samples: 200
  
  # Vocabulary parameters
  vocab_size: 110
  sep_token: 102
  pad_token: 103
  max_length: 32

model:
  d_model: 32
  n_layers: 2
  n_heads: 4
  d_ff: 128  # Smaller for pattern search as in original config
  max_len: 64
  dropout: 0.0  # No dropout for pattern search
  model_count: 8  # Smaller model count for faster experimentation
  init: regular

optimizer:
  name: PatternSearchFast
  
  # Training parameters
  epochs: 80000  
  es_acc: 0.95
  
  # Position offset parameters (disabled by default)
  use_position_offsets: false
  max_position_offset: 16
  
  # Evaluation parameters
  eval_frequency: 50
